
import BUS.CongTyBUS;
import DTO.*;
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Huu
 */
public class ThemCongTyForm extends javax.swing.JFrame {

    /**
     * Creates new form ThemCaNhanForm
     */
    public ThemCongTyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtVAT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radioKhong = new javax.swing.JRadioButton();
        radioCo = new javax.swing.JRadioButton();
        btnXacNhan = new javax.swing.JButton();
        lblThongBao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnThemKhachHang = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm cá nhân");
        setResizable(false);

        jLabel1.setText("Mã số VAT");

        jLabel2.setText("Thuế GTGT");

        radioKhong.setText("Không");
        radioKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioKhongActionPerformed(evt);
            }
        });

        radioCo.setSelected(true);
        radioCo.setText("Có");
        radioCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCoActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Thêm công ty");

        jMenu1.setText("Chức năng");

        jMenuItem2.setText("Trang chủ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        btnThemKhachHang.setText("Thêm khách hàng");
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });
        jMenu1.add(btnThemKhachHang);

        jMenuItem1.setText("Tìm kiếm khách hàng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hệ thống");

        menuExit.setText("Thoát");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu2.add(menuExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioCo)
                        .addGap(41, 41, 41)
                        .addComponent(radioKhong))
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongBao))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radioKhong)
                    .addComponent(radioCo))
                .addGap(35, 35, 35)
                .addComponent(lblThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        this.setVisible(false);
        ThemKhachHangForm themKhachHangForm = new ThemKhachHangForm();
        themKhachHangForm.setVisible(true); 
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String vat = txtVAT.getText();
        int type = -1;
        if(radioCo.isSelected()){
            type = 1;
        }else if(radioKhong.isSelected()){
            type = 0;
        }
        
        if(!vat.isEmpty() && type != -1){            
            CongTyDTO congTyDTO = new CongTyDTO();
            congTyDTO.setTenKh(Global.KhachHangTemp.khachHangDTO.getTenKh());
            congTyDTO.setSoDienThoai(Global.KhachHangTemp.khachHangDTO.getSoDienThoai());
            congTyDTO.setDiaChi(Global.KhachHangTemp.khachHangDTO.getDiaChi());
            congTyDTO.setMaSoVAT(vat);
            congTyDTO .setThueGTGT(type);
            
            if(CongTyBUS.addCaNhan(congTyDTO) > 0){
                lblThongBao.setText("Insert Thành Công");
                lblThongBao.setForeground(Color.YELLOW);
                lblThongBao.setFont(new Font("Dialog", Font.BOLD, 14));
                btnXacNhan.setEnabled(false);
                Global.KhachHangTemp.khachHangDTO.makeEmpty();
            }else{
                lblThongBao.setText("Đã xảy ra lỗi vui lòng thử lại");
                lblThongBao.setForeground(Color.RED); 
            }
            
        }else{
            lblThongBao.setText("Vui lòng nhập đầy đủ thông tin");
            lblThongBao.setForeground(Color.RED); 
        }
        
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void radioCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCoActionPerformed
        if(radioCo.isSelected()){
           radioKhong.setSelected(false);
        }
    }//GEN-LAST:event_radioCoActionPerformed

    private void radioKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKhongActionPerformed
        if(radioKhong.isSelected()){
           radioCo.setSelected(false);
        }
    }//GEN-LAST:event_radioKhongActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        TimKiemKhachHangForm timKiemKhachHangForm = new TimKiemKhachHangForm();
        timKiemKhachHangForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        MainForm main = new MainForm();
        main.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnThemKhachHang;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JRadioButton radioCo;
    private javax.swing.JRadioButton radioKhong;
    private javax.swing.JTextField txtVAT;
    // End of variables declaration//GEN-END:variables
}
